gpt-chat-interview/jobs/urls.py
from django.urls import path

from .views import list_jobs

app_name = "jobs"
urlpatterns = [
    path('', list_jobs, name="list")
]

gpt-chat-interview/setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include("jobs.urls")),
]

gpt-chat-interview/interviews/models.py
import uuid

from django.db import models
from django.conf import settings

from .services import GptService


class Chat(models.Model):
    uuid = models.UUIDField(primary_key=True, editable=False)
    title = models.CharField(max_length=100, editable=False)
    job = models.ForeignKey("jobs.Job", on_delete=models.CASCADE, related_name="chats")
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.uuid:
            self.uuid = uuid.uuid4()
            self.title = f"Chat {self.job.title} - {self.uuid}"
            super().save(*args, **kwargs)
            initial_prompt = settings.INITIAL_PROMPT_TEMPLATE
            initial_prompt = initial_prompt.replace("{job_title}", self.job.title)
            initial_prompt = initial_prompt.replace("{job_requirements}", self.job.requirements)
            initial_prompt = initial_prompt.replace("{job_responsibilities}", self.job.responsibilities)
            Message.objects.create(
                chat=self,
                role="system",
                content=initial_prompt
            )
        super().save(*args, **kwargs)


class Message(models.Model):
    ROLE_CHOICES = (
        ("system", "Sistema"),
        ("user", "Candidato"),
        ("assistant", "Entrevistador")
    )
    
    chat = models.ForeignKey("interviews.Chat", on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=9, choices=ROLE_CHOICES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.role} - {self.chat.title}"

    def save(self, *args, **kwargs):
        if not self.pk and self.role != "assistant" and not self.chat.completed:
            super().save(*args, **kwargs)

            if self.role == "user" and self.chat.messages.filter(role="assistant").count() >= 5:
                Message.objects.create(
                    chat=self.chat,
                    role="system",
                    content="Realize o feedback do candidato, esse feedback deve informar quais foram os pontos positivos, os pontos negativos, o que pode ser melhorado e se o candidato possui um perfil adequado para a vaga."
                )
                self.chat.completed = True
                self.chat.save()
            else:
                service = GptService()
                Message.objects.create(
                    chat=self.chat,
                    role="assistant",
                    content=service.get_chat_completion(self.chat.messages.all())
                )
        else:
            super().save(*args, **kwargs)

gpt-chat-interview/jobs/models.py
from django.db import models


class Job(models.Model):
    LEVEL_CHOICES = (
        ('jr', 'Júnior'),
        ('pl', 'Pleno'),
        ('sr', 'Sênior'),
    )

    title = models.CharField(max_length=100)
    description = models.TextField()
    requirements = models.TextField()
    responsibilities = models.TextField()
    level = models.CharField(max_length=2, choices=LEVEL_CHOICES)
    skills = models.ManyToManyField("jobs.Skill", related_name="jobs")

    def __str__(self):
        return self.title


class Skill(models.Model):
    title = models.CharField(max_length=100, unique=True, blank=False, null=False)

    def __str__(self):
        return self.title

gpt-chat-interview/interviews/views.py
from django.shortcuts import render

# Create your views here.

gpt-chat-interview/jobs/views.py
from django.shortcuts import render

from .models import Job


def list_jobs(request):
    return render(
        request, 
        "jobs/list.html", 
        {
            "page_title": "Lista de Vagas", 
            "jobs": Job.objects.all()
        }
    )

gpt-chat-interview/jobs/templates/jobs/list.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <title>TWJobs - {{ page_title }}</title>

  <style>
    .card-area {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 30px;
    }

    .card {
      max-height: 300px;
      overflow: hidden;
    }

    .card-body {
      display: flex;
      flex-direction: column;
    }

    .card-body .links {
      margin-top: auto;
    }

    .card h5 {
      overflow: hidden;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      line-clamp: 3;
      -webkit-box-orient: vertical;
    }
  </style>
</head>
<body>
    <nav class="navbar bg-dark" data-bs-theme="dark">
      <div class="container">
        <a href="" class="navbar-brand">
          <img 
            src="https://github.com/treinaweb.png" 
            alt="logo da TreinaWeb" 
            width="24" 
            height="24"
            class="d-inline-block align-text-top"
          >
          TWJobs
        </a>
      </div>
    </nav>

    <main>
      <section class="py-5">
        <div class="container">
          <h1>{{ page_title }}</h1>

          <div class="card-area mt-4 px-2">
            {% for job in jobs %}
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title fw-bolder">
                    {{ job.title }}
                  </h5>
                  <h6 class="card-subtitle mb-2 text-body secondary">{{ job.get_level_display }}</h6>
                  <p class="card-text">
                    {% for skill in job.skills.all %}
                      <span class="badge text-bg-primary">{{ skill.title }}</span>
                    {% endfor %}
                  </p>
                  <div class="links">
                    <a href="" class="mt-4">Detalhes</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </section>
    </main>

    <footer class="bg-dark fixed-bottom">
      <div class="container">
        <p class="text-white text-center m-0 py-3">
          TreinaWeb
        </p>
      </div>
    </footer>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>